# Generated by Django 2.2.6 on 2019-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andersen', '0005_auto_20191002_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referral',
            field=models.ManyToManyField(related_name='clients', to='andersen.Referral'),
        ),
        migrations.AlterField(
            model_name='client',
            name='value',
            field=models.IntegerField(),
        ),
    ]
