# Generated by Django 2.2.6 on 2019-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andersen', '0006_auto_20191003_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referral',
            field=models.ManyToManyField(related_name='clients', to='andersen.Referral'),
        ),
    ]
