# Generated by Django 2.2.6 on 2019-10-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andersen', '0007_auto_20191003_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='referral',
        ),
        migrations.AddField(
            model_name='client',
            name='referral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='andersen.Referral'),
            preserve_default=False,
        ),
    ]
