# Generated by Django 2.2.6 on 2019-10-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andersen', '0016_auto_20191003_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='andersen.Referral'),
        ),
    ]
